config/routes.rb
DtvClient::Application.routes.draw do
  resources :series, only: [:index, :show] do
    resources :episodes

    get :search, on: :collection
  end
  resources :pages, only: [:index, :show]

  root :to => 'pages#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessor :serie, :title

  def title= value
    @title = value.gsub(/-/, ' ').humanize
  end

  def full_episode_title
    "#{serie.name} - Season #{season} - #{title}"
  end

  def season
    [*1..10].sample
  end

  def number
    [*1..25].sample
  end

  def numbering
    "S#{"%02d" % season}E#{number}"
  end

  def to_param
    title.parameterize
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < SerieAreaController
  def show
    @episode = Episode.new( serie: @serie, title: params[:id] )

    @episodes = []
    12.times do |e|
      @episodes << Episode.new( serie: @serie, title: @demo[:episode_titles].sample )
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to series_path( Serie.first )
  end

  def show
    render params[:id]
  end
end

app/controllers/serie_area_controller.rb
class SerieAreaController < ApplicationController
  before_filter :get_serie

  private
  def get_serie
    @serie = Serie.find(params[:series_id])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  respond_to :json
  def index
    respond_with @demo[:series]
  end

  def show
    @serie = Serie.find params[:id]
  end

  def search
    @series = Serie.search(params[:query]).all

    redirect_to @series.first if @series.length == 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/_buttons.haml
.episode-controls.btn-toolbar
  .btn-group
    %a.btn.btn-info Search
    %a.btn.btn-info.dropdown-toggle{data: {toggle: :dropdown}}
      %span.caret
    %ul.dropdown-menu
      %li= link_to 'Search low res'
      %li= link_to 'Seach HD'
  .btn-group
    %a.btn.btn-success Download
    %a.btn.btn-success.dropdown-toggle{data: {toggle: :dropdown}}
      %span.caret
    %ul.dropdown-menu
      %li= link_to 'Download low res'
      %li= link_to 'Download HD'

app/views/episodes/_past_episode.haml
- serie = Serie.find_by_name @demo[:series].sample
- episode = @demo[:episode_titles].sample
%li.episode
  %h4
    = link_to serie.name, serie
    \- 
    = link_to episode, series_episode_path(serie, episode.parameterize)
  .row-fluid
    .span8.pull-left
      %p.description
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      - if @logged_in
        = render 'episodes/buttons'
    .span4
      %img.pull-right{src: @demo[:episode_images].sample, width: 260, height: 180}

app/views/episodes/show.haml
.span10
  %header
    %ul.breadcrumb
      %li
        = link_to 'Home', root_path
        %span.divider /
      %li
        = link_to 'Series', root_path
        %span.divider /
      %li
        = link_to @serie.name, @serie
        %span.divider /
      %li= link_to @episode.title, series_episode_path(@serie, @episode)
      %li.pull-right
        = link_to 'Next episode', series_episode_path(@serie, @demo[:episode_titles].sample.parameterize)
      %li.pull-right
        = link_to 'Previous episode', series_episode_path(@serie, @demo[:episode_titles].sample.parameterize)
        %span.divider= "|"

  .row-fluid
    .span12
      %h1= @episode.full_episode_title
      .panel
        .row
          .span4
            %img{ src: @serie.fanart.first }
          .span7
            %dl
              %dt Description
              %dd 
                %p 
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              %dt Airdate
              %dd= [*-100..100].sample.days.ago.to_date.to_s(:long)
              %dt Episode number
              %dd= @episode.number
            - if @logged_in
              = render partial: 'episodes/buttons'

  %h2 Other episodes this season
  .alert.alert-info
    %span.label.label-info Notice
    Any better ideas? With the final implementation the row should be highlighted
  = render partial: 'series/season'