config/routes.rb
DtvClient::Application.routes.draw do
  resources :series, only: [:index, :show] do
    resources :episodes

    get :search, on: :collection
  end
  resources :pages, only: [:index, :show]

  root :to => 'pages#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessor :serie, :title

  def title= value
    @title = value.gsub(/-/, ' ').humanize
  end

  def full_episode_title
    "#{serie.name} - Season #{season} - #{title}"
  end

  def season
    [*1..10].sample
  end

  def number
    [*1..25].sample
  end

  def numbering
    "S#{"%02d" % season}E#{number}"
  end

  def to_param
    title.parameterize
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < SerieAreaController
  def show
    @episode = Episode.new( serie: @serie, title: params[:id] )

    @episodes = []
    12.times do |e|
      @episodes << Episode.new( serie: @serie, title: @demo[:episode_titles].sample )
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to series_path( Serie.first )
  end

  def show
    render params[:id]
  end
end

app/controllers/serie_area_controller.rb
class SerieAreaController < ApplicationController
  before_filter :get_serie

  private
  def get_serie
    @serie = Serie.find(params[:series_id])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  respond_to :json
  def index
    respond_with @demo[:series]
  end

  def show
    @serie = Serie.find params[:id]
  end

  def search
    @series = Serie.search(params[:query]).all

    redirect_to @series.first if @series.length == 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/pages/guide.html.haml
.span10
  %header
    %ul.breadcrumb
      %li
        = link_to 'Home', root_path
        %span.divider /
      %li
        - if @logged_in
          = link_to 'My Stations', root_path
        - else
          = link_to 'Stations', root_path
        %span.divider /
      %li= link_to 'All', page_path(:guide)
    %h1== Station - All #{'my' if @logged_in} stations
  .row-fluid
    .span8
      %header
        %h2 Just aired episodes

      - unless @logged_in
        .alert.alert-block.alert-info.fade.in
          %a.close{data: {dismiss: 'alert'}} &times;
          %h4.alert-heading You are not logged in
          %p 
            If you identify yourself we could save your preferences for you. Until then this guide will be shown as the full guide. To register yourself only a name and password are needed.
      %section#past_episodes
        %ul.nav.nav-list
          - 10.times do |i|
            %li.nav-header
              %h4= i.days.ago.to_date.to_s(:long)
            - (1..5).to_a.sample.times do
              = render 'episodes/past_episode'
    .span4
      %header
        %h2 Upcoming episodes
      %section#upcoming-episodes
        .well
          .nav.nav-list
            %dl
              - 10.times do |i|
                %dt.nav-header= i.days.ago.to_date.to_s(:long)
                - (1..5).to_a.sample.times do
                  %dd
                    - serie = Serie.find_by_name @demo[:series].sample
                    = link_to serie.name, serie
                    - case (1..100).to_a.sample
                      - when 1..3
                        %span.info.label.label-success New
                      - when 10..20
                        %span.info.label.label-success New season

app/views/pages/index.html.haml
- episode_titles = ["Tarantella", "Episode 2", "Lethal Weapons", "Vegas Baby, Vegas!", "Gambon Corner Gets Its Name", "The Yoga Bear", "Group Four! Then the Wild Card!", "The Sentimental Bloke", "Chuck Versus the Cat Squad", "Senior's Vintage Project 2", "The Naked Man", "Ronnie Corbett, Greg Kinnear, Shaun Williamson and Ricky Gervais", "Episode 13", "First Kiss", "Here We Go Again", "When the Levee Breaks", "The Futurama Holiday Spectacular", "No Ordinary Accident", "The Vest", "Social Psychology", "The Day of the Clown (2)", "Double Jeopardy", "The Monster Within", "Chuck Versus the Cougars", "A Better Human Being", "Black Pearl", "Under God's Power She Flourishes", "The Girl Next Door ", "Baby Boom", "Heart of Glass", "Sucker Punch", "By the Book", "Lance Armstrong Bike 1", "Past Tense", "A Possum on Chemo", "Pleased to Meet Me", "Red-Handed", "Throwdown", "First practice! Vigorous Kazuya & worn-out Tatsuya!?", "J-Cat", "Tucson, AZ 1", "The Top Gear Generation Game", "Stone Mountain", "Episode 3", "Table Cloth Chaos", "Gilted Lily", "No Good Deed", "TBA", "The Monster at the End of this Book", "The Fight"]
.span10
  %header
    %ul.breadcrumb
      %li
        = link_to 'Home', root_path
        %span.divider /
      %li
        = link_to 'Programs', root_path
        %span.divider /
      %li= link_to 'MythBusters', pages_path(id: 'program')
      %li.pull-right= link_to 'Next serie'
      %li.pull-right
        = link_to 'Previous serie'
        %span.divider= "|"
  .row-fluid
    .span9
      %header
        %h1 MythBusters
      %section#serie-graphics
        .carousel.slide
          .carousel-inner
            .item.active{style: 'background-image: url(http://images.jewilmeer.com/tvdb_images/10413/original_1320285611.jpg?1320285611)'}
            .item{style: 'background-image: url(http://images.jewilmeer.com/tvdb_images/10417/original_1328358672.jpg?1328358672)'}
      %section#season-detail
        %h3 Season details
        - nr_of_seasons = (1..10).to_a.sample
        .tabbable.tabs-left
          .row-fluid
            .span2
              %ul.nav.nav-tabs
                - nr_of_seasons.times do |i|
                  - if i.succ == nr_of_seasons #last
                    %li.active= link_to "Season #{i.succ}", "#season-#{i.succ}", data: {toggle: :tab}
                  - else
                    %li= link_to "Season #{i.succ}", "#season-#{i.succ}", data: {toggle: :tab}
            .span10
              .tab-content
                - nr_of_seasons.times do |i|
                  - if i.succ == nr_of_seasons #last
                    .tab-pane.fade.active.in{id: "season-#{i.succ}"}
                      %table.table.table-bordered.table-striped 
                        %thead
                          %tr
                            %th Name
                            %th Airdate
                        %tbody
                          - nr_of_episodes = (6..22).to_a.sample.times do |i|
                            %tr
                              %td= link_to episode_titles.sample, ''
                              %td= i.weeks.ago.to_date.to_s(:long)
                  - else
                    .tab-pane.fade{id: "season-#{i.succ}"}
                      %table.table.table-bordered.table-striped 
                        %thead
                          %tr
                            %th Name
                            %th Airdate
                        %tbody
                          - nr_of_episodes = (6..22).to_a.sample.times do |i|
                            %tr
                              %td= link_to episode_titles.sample, ''
                              %td= i.weeks.ago.to_date.to_s(:long)
            
    .span3.pull-right
      %section#recommendations
        .panel
          %h4 You might also like
          %ul.unstyled
            %li= link_to 'Brainiac'
            %li= link_to 'An Idiot Abroad'
            %li= link_to 'Top Gear'
          .alert.alert-notice
            %span.label.label-notice Notice
            Needs pictures instead of text
      %section#user-details
        = render partial: 'series/tags'
      %section#program-details
        .panel
          %h4 Additional information
          %dl
            %dt Genres
            %dd 
              - linked_genres = ['Science', 'Comedy'].map{|genre| link_to genre, '#' }
              = linked_genres.to_sentence.html_safe
            %dt Actors
            %dd 
              - linked_actors = ['James dingus', 'Adam Savage'].map{|actor| link_to actor, '#' }
              = linked_actors.to_sentence.html_safe
            %dt Poularity
            %dd== #{(1..100).to_a.sample}%