config/routes.rb
DtvClient::Application.routes.draw do
  resources :series, only: [:index, :show] do
    resources :episodes

    get :search, on: :collection
  end
  resources :pages, only: [:index, :show]

  root :to => 'pages#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  attr_accessor :serie, :title

  def title= value
    @title = value.gsub(/-/, ' ').humanize
  end

  def full_episode_title
    "#{serie.name} - Season #{season} - #{title}"
  end

  def season
    [*1..10].sample
  end

  def number
    [*1..25].sample
  end

  def numbering
    "S#{"%02d" % season}E#{number}"
  end

  def to_param
    title.parameterize
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < SerieAreaController
  def show
    @episode = Episode.new( serie: @serie, title: params[:id] )

    @episodes = []
    12.times do |e|
      @episodes << Episode.new( serie: @serie, title: @demo[:episode_titles].sample )
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to series_path( Serie.first )
  end

  def show
    render params[:id]
  end
end

app/controllers/serie_area_controller.rb
class SerieAreaController < ApplicationController
  before_filter :get_serie

  private
  def get_serie
    @serie = Serie.find(params[:series_id])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  respond_to :json
  def index
    respond_with @demo[:series]
  end

  def show
    @serie = Serie.find params[:id]
  end

  def search
    @series = Serie.search(params[:query]).all

    redirect_to @series.first if @series.length == 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.haml
%nav.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{data: {toggle: 'collapse', target: '.nav-collapse'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'DTV Client', root_path, class: :brand
      .nav-collapse
        %ul.nav
          %li= link_to 'Guide', page_path(id: :guide)
          %li= link_to 'Episodes', '#'
        = form_for :program, url: search_series_index_url, html: {class: %(navbar-search pull-left), method: :get} do
          %input.search-query{placeholder: 'Search', name: :query, autocomplete: :off}
        %ul.nav.pull-right
          - if @logged_in
            %li= link_to 'Logout', url_for( params.merge(login: false) )
          - else
            %li= link_to 'Login', url_for( params.merge(login: true) )

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title Dtv client
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    %meta{name: :viewport, content: 'width=device-width, initial-scale=1.0'}

  %body
    = render 'layouts/navbar'
    .container-fluid
      .row-fluid
        .span2
          #sidebar.well{style: 'padding: 8px 0'}
            %ul.nav.nav-list
              %li.nav-header My stations
              %li{class: (:active if params[:id] == 'guide' && @logged_in)}= link_to 'All episodes', page_path(:guide)
              %li= link_to 'Starred', ''
              - if @logged_in
                %li= link_to 'Snack', ''
                %li= link_to 'To be sorted', ''
                %li= link_to 'Recommended', ''
                %li= link_to 'Little bit to long for this just as a test', ''
              %li.nav-header Other stations
              %li{class: (:active if params[:id] == 'guide' && !@logged_in)}= link_to 'All episodes', page_path(:guide)
              %li= link_to 'Best rated'
              %li= link_to 'SciFi'
              %li.nav-header Other user stations
              %li= link_to 'Steef\'s snack station'
              %li= link_to 'JW\'s Chick station'
        = yield              